# Generated by Django 5.0.2 on 2024-02-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record_entry_NID',
            fields=[
                ('nid_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('father_name', models.CharField(default=None, max_length=100)),
                ('mother_name', models.CharField(default=None, max_length=100)),
                ('birthmark', models.CharField(default=None, max_length=100)),
                ('extraIdentificationMark', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=200)),
                ('phone_number', models.CharField(max_length=11)),
                ('crime_type', models.CharField(default=None, max_length=50)),
                ('crime_location', models.CharField(default=None, max_length=200)),
                ('crime_date_time', models.DateTimeField()),
                ('crime_status', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
