# Generated by Django 5.0.2 on 2024-02-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0002_record_entry_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_entry_dob',
            old_name='DOB_number',
            new_name='Birth_certification_number',
        ),
    ]
