# Generated by Django 5.0.2 on 2024-02-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authantication', '0004_remove_authantication_id_and_more'),
        ('crime_record_check', '0004_alter_record_entry_dob_birth_certification_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureCodeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('secure_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authantication.authantication')),
            ],
        ),
    ]
