# Generated by Django 5.0.2 on 2024-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0005_securecodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_entry_nid',
            name='nid_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
