# Generated by Django 5.0.2 on 2024-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0006_alter_record_entry_nid_nid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_entry_dob',
            name='picture',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='record_entry_nid',
            name='picture',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
