# Generated by Django 5.0.2 on 2024-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0007_record_entry_dob_picture_record_entry_nid_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_entry_dob',
            name='picture',
            field=models.ImageField(default=False, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='record_entry_nid',
            name='picture',
            field=models.ImageField(default=False, upload_to='images'),
        ),
    ]
