# Generated by Django 5.0.2 on 2024-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0008_alter_record_entry_dob_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_entry_nid',
            name='picture',
            field=models.ImageField(default=False, upload_to='img'),
        ),
    ]
