# Generated by Django 5.0.2 on 2024-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0009_alter_record_entry_nid_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_entry_dob',
            name='picture',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='record_entry_nid',
            name='picture',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='img'),
        ),
    ]
