# Generated by Django 5.0.2 on 2024-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_record_check', '0010_alter_record_entry_dob_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_entry_dob',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='record_entry_nid',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
