# Generated by Django 5.0.2 on 2024-02-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authantication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authantication',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
